---
- hosts: apache

  vars:
      moj_user: szkolenie17

  tasks:
    - name: "utworz directory"
      file:
          path: "~/stworzmnie{{ moj_user }}"
          state: directory 

    - name: "sprawdz czy plik isnieje"
      stat:
        path: "~/stworzmnie{{ moj_user }}"
      register: zmienna

    - name: "utworz plik jesli nie isnieje"
      file:
          path: "~/stworzmnie{{ moj_user }}/plik"
          state: touch
      when: not zmienna.stat.exists

