- hosts: naszaaplikacja_loadbalancer

  vars:
    katalog_glowny: /var/www/szkolenie
    katalog_aplikacji: "{{ katalog_glowny }}/aplikacja"

#### apache na wybranym porcie

  become: true

  #zmienne przydatne do parametryzacji wgrania, oraz szablonowania konfiguracji
  #vars:
  #  katalog_aplikacji: /var/www/szkolenie
  #  log_dir: /var/www/szkolenie/logs/
  #  port: 5001

  pre_tasks: []

  roles:
    - przykladowy_loadbalancer

